name:                adventofcode
version:             0.1.0.0
github:              "pdcxs/adventofcode"
license:             BSD-3-Clause
author:              "pdcxs"
maintainer:          "pdcxs@outlook.com"
copyright:           "2024 pdcxs"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pdcxs/adventofcode#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- filepath
- vector
- parsec
- array
- mtl
- split
- MemoTrie
- text
- sdl2
- sdl2-ttf
- linear
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  adventofcode-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
    when:
    - condition: false
      other-modules: Paths_adventofcode

tests:
  adventofcode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
